INSERT INTO gyd_forums VALUES ('50','SONY ERICSON','0','0','6');
INSERT INTO gyd_forums VALUES ('4','Network Cheatz','2','4','0');
INSERT INTO gyd_forums VALUES ('5','Introduce YourSelf','1','1','0');
INSERT INTO gyd_forums VALUES ('57','FUN','0','0','11');
INSERT INTO gyd_forums VALUES ('7','Alarm On Bugs','3','1','0');
INSERT INTO gyd_forums VALUES ('8','Computers','3','4','0');
INSERT INTO gyd_forums VALUES ('9','Phones','3','4','0');
INSERT INTO gyd_forums VALUES ('10','Chelsea FC','3','2','0');
INSERT INTO gyd_forums VALUES ('11','Arsenal FC','3','2','0');
INSERT INTO gyd_forums VALUES ('12','ManU','3','2','0');
INSERT INTO gyd_forums VALUES ('26','Movies','0','3','0');
INSERT INTO gyd_forums VALUES ('14','Latest Gistz','3','3','0');
INSERT INTO gyd_forums VALUES ('15','Jokes','3','3','0');
INSERT INTO gyd_forums VALUES ('16','For Sale','3','5','0');
INSERT INTO gyd_forums VALUES ('17','For Buy','3','5','0');
INSERT INTO gyd_forums VALUES ('19','Wapmaster's Talk','2','4','0');
INSERT INTO gyd_forums VALUES ('21','General Sports','1','2','0');
INSERT INTO gyd_forums VALUES ('22','Booty Call','0','6','0');
INSERT INTO gyd_forums VALUES ('23','Love','0','6','0');
INSERT INTO gyd_forums VALUES ('24','Love Quotes','0','6','0');
INSERT INTO gyd_forums VALUES ('25','General','0','6','0');
INSERT INTO gyd_forums VALUES ('27','Celebrities','0','3','0');
INSERT INTO gyd_forums VALUES ('28','Music','0','3','0');
INSERT INTO gyd_forums VALUES ('29','Internet','0','4','0');
INSERT INTO gyd_forums VALUES ('52','Man U FANS','0','0','8');
INSERT INTO gyd_forums VALUES ('31','Jobs','1','7','0');
INSERT INTO gyd_forums VALUES ('32','Services','0','5','0');
INSERT INTO gyd_forums VALUES ('33','Housing and Rentals','4','5','0');
INSERT INTO gyd_forums VALUES ('34','Education','0','7','0');
INSERT INTO gyd_forums VALUES ('35','Business','0','7','0');
INSERT INTO gyd_forums VALUES ('36','Politics','0','7','0');
INSERT INTO gyd_forums VALUES ('37','Latest News','0','7','0');
INSERT INTO gyd_forums VALUES ('38','Religions','0','7','0');
INSERT INTO gyd_forums VALUES ('39','Culture','0','7','0');
INSERT INTO gyd_forums VALUES ('40','Literature/Writing','0','7','0');
INSERT INTO gyd_forums VALUES ('41','Fashion','0','3','0');
INSERT INTO gyd_forums VALUES ('42','Graphics','0','4','0');
INSERT INTO gyd_forums VALUES ('43','Liverpool FC','5','2','0');
INSERT INTO gyd_forums VALUES ('44','Barca FC','6','2','0');
INSERT INTO gyd_forums VALUES ('45','Quiz','5','3','0');
INSERT INTO gyd_forums VALUES ('46','hunter','0','0','2');
INSERT INTO gyd_forums VALUES ('47','Barcelona Fc','0','0','3');
INSERT INTO gyd_forums VALUES ('48','General Talks','0','0','4');
INSERT INTO gyd_forums VALUES ('49','Gunners fans','0','0','5');
INSERT INTO gyd_forums VALUES ('53','Adult (18+)','2','6','0');
INSERT INTO gyd_forums VALUES ('54','Hacking/Cracking','2','4','0');
INSERT INTO gyd_forums VALUES ('56','Joy','0','0','10');
INSERT INTO gyd_forums VALUES ('58','YORUBA PEOPLE CLUB','0','0','12');
INSERT INTO gyd_forums VALUES ('59','Pn0y-wapBies aDik','0','0','13');
INSERT INTO gyd_forums VALUES ('60','Hottest Dancers','0','0','14');
INSERT INTO gyd_forums VALUES ('61','Deneros','0','0','15');
INSERT INTO gyd_forums VALUES ('65','Gunner','0','0','19');
INSERT INTO gyd_forums VALUES ('66','Northern zone','0','0','20');
INSERT INTO gyd_forums VALUES ('72','Kwara People','0','0','26');
INSERT INTO gyd_forums VALUES ('68','ROTARY CLUB OF NIG.','0','0','22');
INSERT INTO gyd_forums VALUES ('70','THE GREAT 9JA','0','0','24');
