INSERT INTO gyd_blockedsite VALUES ('3','xgammer.com');
INSERT INTO gyd_blockedsite VALUES ('4','wapcult');
INSERT INTO gyd_blockedsite VALUES ('6','WAPC');
INSERT INTO gyd_blockedsite VALUES ('7','wapcult.com');
INSERT INTO gyd_blockedsite VALUES ('8','Magicalwap');
INSERT INTO gyd_blockedsite VALUES ('9','magicalwap');
INSERT INTO gyd_blockedsite VALUES ('10','w a p c u l t');
INSERT INTO gyd_blockedsite VALUES ('81','newbies.');
INSERT INTO gyd_blockedsite VALUES ('13','.co.cc');
INSERT INTO gyd_blockedsite VALUES ('14','.cc');
INSERT INTO gyd_blockedsite VALUES ('15','.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('85','Livingstone.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('17','W A P C U L T');
INSERT INTO gyd_blockedsite VALUES ('18','WaPcUlT');
INSERT INTO gyd_blockedsite VALUES ('19','w,a,p,c,u,l,t');
INSERT INTO gyd_blockedsite VALUES ('20','.wen.ru');
INSERT INTO gyd_blockedsite VALUES ('21','wen.ru');
INSERT INTO gyd_blockedsite VALUES ('22','mufdotmubi');
INSERT INTO gyd_blockedsite VALUES ('82','w2c.mobi');
INSERT INTO gyd_blockedsite VALUES ('26','dot muf dot mobi');
INSERT INTO gyd_blockedsite VALUES ('27','naijaboiz.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('28','osamu.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('29','join.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('30','join.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('31','9jappl4rum');
INSERT INTO gyd_blockedsite VALUES ('32','9jappl4rum.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('33','frndzchat');
INSERT INTO gyd_blockedsite VALUES ('34','waptricks.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('35','frndzchat.com');
INSERT INTO gyd_blockedsite VALUES ('36','waptrick.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('37','frndzchat dot com');
INSERT INTO gyd_blockedsite VALUES ('38','ficozone.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('39','faladesesan.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('40','frndzchat DOTcom');
INSERT INTO gyd_blockedsite VALUES ('41','FrndzChat.com');
INSERT INTO gyd_blockedsite VALUES ('42','wapirate.net');
INSERT INTO gyd_blockedsite VALUES ('43','FrndzChat');
INSERT INTO gyd_blockedsite VALUES ('44','kazwap');
INSERT INTO gyd_blockedsite VALUES ('45','kazwap.net');
INSERT INTO gyd_blockedsite VALUES ('46','arawap.net');
INSERT INTO gyd_blockedsite VALUES ('47','Arawap.net');
INSERT INTO gyd_blockedsite VALUES ('48','araWap.net');
INSERT INTO gyd_blockedsite VALUES ('49','araWap');
INSERT INTO gyd_blockedsite VALUES ('50','wapcrack.net');
INSERT INTO gyd_blockedsite VALUES ('51','wapcrackDOTnet');
INSERT INTO gyd_blockedsite VALUES ('52','wapcrack');
INSERT INTO gyd_blockedsite VALUES ('53','mobenrich');
INSERT INTO gyd_blockedsite VALUES ('54','9jawap');
INSERT INTO gyd_blockedsite VALUES ('55','wap.net.ph');
INSERT INTO gyd_blockedsite VALUES ('57','latwap');
INSERT INTO gyd_blockedsite VALUES ('58','Latwap');
INSERT INTO gyd_blockedsite VALUES ('59','winwap');
INSERT INTO gyd_blockedsite VALUES ('60','wapzan');
INSERT INTO gyd_blockedsite VALUES ('61','Wapzan');
INSERT INTO gyd_blockedsite VALUES ('62','coding-talk');
INSERT INTO gyd_blockedsite VALUES ('63','landofwap');
INSERT INTO gyd_blockedsite VALUES ('64','lordofwap');
INSERT INTO gyd_blockedsite VALUES ('65','faceofnaija');
INSERT INTO gyd_blockedsite VALUES ('66','blingywap');
INSERT INTO gyd_blockedsite VALUES ('67','mobile.web.tr');
INSERT INTO gyd_blockedsite VALUES ('68','onmbl.com');
INSERT INTO gyd_blockedsite VALUES ('69','magicalwap.com');
INSERT INTO gyd_blockedsite VALUES ('83','w2c');
INSERT INTO gyd_blockedsite VALUES ('84','kvwap.com');
INSERT INTO gyd_blockedsite VALUES ('75','dmpsites');
INSERT INTO gyd_blockedsite VALUES ('76','dmpsite');
INSERT INTO gyd_blockedsite VALUES ('77','wapdesire');
INSERT INTO gyd_blockedsite VALUES ('78','darkdesire');
INSERT INTO gyd_blockedsite VALUES ('86','solutionz.wapka.mobi');
INSERT INTO gyd_blockedsite VALUES ('80','chatx');
INSERT INTO gyd_blockedsite VALUES ('87','wapka.mobi');
INSERT INTO gyd_blockedsite VALUES ('88','wapka dot mobi');
INSERT INTO gyd_blockedsite VALUES ('89','solutionz dot wapka dot mobi');
INSERT INTO gyd_blockedsite VALUES ('90','dum,su');
INSERT INTO gyd_blockedsite VALUES ('91','dwap,dum,su');
INSERT INTO gyd_blockedsite VALUES ('92','dwap.dum.su');
INSERT INTO gyd_blockedsite VALUES ('93','dum.su');
INSERT INTO gyd_blockedsite VALUES ('94','dum dot su');
INSERT INTO gyd_blockedsite VALUES ('95','dwap.');
INSERT INTO gyd_blockedsite VALUES ('96','9jappl4rm');
INSERT INTO gyd_blockedsite VALUES ('97','9jappl4');
INSERT INTO gyd_blockedsite VALUES ('98','9jadownloads.wap9.mobi');
INSERT INTO gyd_blockedsite VALUES ('99','9jadownloads.');
INSERT INTO gyd_blockedsite VALUES ('100','9jaboiz.muf.mobi');
INSERT INTO gyd_blockedsite VALUES ('101','wap9.mobi');
INSERT INTO gyd_blockedsite VALUES ('102','ficozone');
INSERT INTO gyd_blockedsite VALUES ('103','ficozone.onbl.net');
INSERT INTO gyd_blockedsite VALUES ('104','9,j,a,w,a,p,');
INSERT INTO gyd_blockedsite VALUES ('105','9jawap.net');
INSERT INTO gyd_blockedsite VALUES ('106','9jawap,net');
INSERT INTO gyd_blockedsite VALUES ('107','.mobi');
INSERT INTO gyd_blockedsite VALUES ('108','ninjawap');
INSERT INTO gyd_blockedsite VALUES ('109','jawap');
INSERT INTO gyd_blockedsite VALUES ('110','9.j.a.w.a.p');
INSERT INTO gyd_blockedsite VALUES ('111','9 j a w a p');
INSERT INTO gyd_blockedsite VALUES ('112','9JAWAP');
INSERT INTO gyd_blockedsite VALUES ('113','9JAWAP.NET');
INSERT INTO gyd_blockedsite VALUES ('114','9 J a W a P');
INSERT INTO gyd_blockedsite VALUES ('115','vinhat dot com');
INSERT INTO gyd_blockedsite VALUES ('116','DWAP');
INSERT INTO gyd_blockedsite VALUES ('117','D WAP');
INSERT INTO gyd_blockedsite VALUES ('118','WEN 9');
INSERT INTO gyd_blockedsite VALUES ('119','W E N');
INSERT INTO gyd_blockedsite VALUES ('120','w e n');
INSERT INTO gyd_blockedsite VALUES ('121','d w a p');
INSERT INTO gyd_blockedsite VALUES ('122','W E N . R U');
INSERT INTO gyd_blockedsite VALUES ('123','laptop.com');
INSERT INTO gyd_blockedsite VALUES ('124','/?=');
INSERT INTO gyd_blockedsite VALUES ('125','/index.php?');
INSERT INTO gyd_blockedsite VALUES ('126','/index.php?');
INSERT INTO gyd_blockedsite VALUES ('127','magicalwap');
INSERT INTO gyd_blockedsite VALUES ('128','m a g i c a l w a p');
INSERT INTO gyd_blockedsite VALUES ('129','MAGICALWAP');
INSERT INTO gyd_blockedsite VALUES ('130','M A G I C A L W A P');
INSERT INTO gyd_blockedsite VALUES ('131','m.a.g.i.c.a.l.w.a.p');
INSERT INTO gyd_blockedsite VALUES ('132','m_a_g_i_c_a_l_w_a_p');
INSERT INTO gyd_blockedsite VALUES ('133','magical wap');
INSERT INTO gyd_blockedsite VALUES ('134','angelworlds.net');
INSERT INTO gyd_blockedsite VALUES ('135','angelworlds');
INSERT INTO gyd_blockedsite VALUES ('136','a n g e l w o r l d s');
INSERT INTO gyd_blockedsite VALUES ('137','a-n-g-e-l-w-o-r-l-d-s');
INSERT INTO gyd_blockedsite VALUES ('138','a.n.g.e.l.w.o.r.l.d.s');
INSERT INTO gyd_blockedsite VALUES ('139','wapbies.p.a.mobi');
INSERT INTO gyd_blockedsite VALUES ('140','.mobi');
INSERT INTO gyd_blockedsite VALUES ('141','.uni.cc');
INSERT INTO gyd_blockedsite VALUES ('142','9jacheat.');
INSERT INTO gyd_blockedsite VALUES ('143','9jacheat dot');
INSERT INTO gyd_blockedsite VALUES ('144','9jacheatdot');
INSERT INTO gyd_blockedsite VALUES ('145','9jabliss');
INSERT INTO gyd_blockedsite VALUES ('146','onmbl');
INSERT INTO gyd_blockedsite VALUES ('147','dotnet');
INSERT INTO gyd_blockedsite VALUES ('148','dot net');
