INSERT INTO gyd_moods VALUES ('1','[:-(]','moods/angry.gif','Angry');
INSERT INTO gyd_moods VALUES ('2','[:D]','moods/happy.gif','big grin');
INSERT INTO gyd_moods VALUES ('3','[:?]','moods/confused.gif','Confused');
INSERT INTO gyd_moods VALUES ('4','[8)]','moods/cool.gif','Cool');
INSERT INTO gyd_moods VALUES ('5','[=P]','moods/disgust.gif','Disgusts/ like yeah whatever');
INSERT INTO gyd_moods VALUES ('6','[:*]','moods/nasty.gif','Nasty/Drools');
INSERT INTO gyd_moods VALUES ('7','[>:)]','moods/evil.gif','Evil');
INSERT INTO gyd_moods VALUES ('8','[:/]','moods/careless.gif','Careless/Angry/Disappointed');
INSERT INTO gyd_moods VALUES ('9','[:(]','moods/sad.gif','Sad');
INSERT INTO gyd_moods VALUES ('10','[~:(]','moods/grr.gif','GRRR/Angry /Mad');
INSERT INTO gyd_moods VALUES ('11','[:8)]','moods/shy.gif','Shy/redface/blushing');
INSERT INTO gyd_moods VALUES ('12','[:O]','moods/retard.gif','Retard/eek/going huh');
INSERT INTO gyd_moods VALUES ('13','[:)]','moods/smile.gif','Smiling/Happy');
INSERT INTO gyd_moods VALUES ('14','[:,(]','moods/cry.gif','Crying');
INSERT INTO gyd_moods VALUES ('15','[x-(]','moods/dead.gif','Dead');
INSERT INTO gyd_moods VALUES ('16','[=D]','moods/happy.gif','Happy');
INSERT INTO gyd_moods VALUES ('17','[8(,]','moods/sick.gif','Sick/ Tired/ Sour');
INSERT INTO gyd_moods VALUES ('18','[3(]','moods/sleep.gif','Sleeping / Sleepy');
INSERT INTO gyd_moods VALUES ('19','[(:(]','moods/sorry.gif','Sorry');
